# Generated by Django 4.2 on 2023-05-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant that this review is for.', on_delete=django.db.models.deletion.CASCADE, to='app.restaurants'),
        ),
    ]
