# Generated by Django 4.2 on 2023-05-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_menu_title_alter_review_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='reviews',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='description',
            field=models.CharField(default='...', max_length=650),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='work_time',
            field=models.CharField(default='9:00 am - 22:00 pm', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
