# Generated by Django 4.2 on 2023-05-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_review_content_alter_review_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='name',
            new_name='title',
        ),
    ]
